-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCkHqV1XDpim5Q8qn
MZNJXoCuj1C+gwg7esKtfGKzu+WgCgYIKoZIzj0DAQehRANCAASt2hvLAVPKcyPn
1RviKX+ylTjIUfaoFmsdQ0140DoDCd6FTlEq7rGPsVX0LuYVT7cfQQGVcq/cEl2s
UeOcsWhf
-----END PRIVATE KEY-----