export enum ServerMessagesEnum {
    "server-error" = "server-error",
    "no-file-provided" = "no-file-provided",
    "not-found" = "not-found",
    "required-iv" = "required-iv",
    "permission-denied" = "permission-denied",
    "user-bc" = "user-bc",
    "user-bl" = "user-bl",
    "user-dl" = "user-dl",
    "user-it" = "user-it",
    "user-ua" = "user-ua",
    "user-nf" = "user-nf",
    "email-already-exists" = "email-already-exists",
    "invalid-password" = "invalid-password",
    "logged-in" = "logged-in",
    "user-fetched" = "user-fetched",
    "user-add" = "user-add",
    "user-update" = "user-update",
    "user-delete" = "user-delete",
    "user-status" = "user-status",
    "notifications-fetched" = "notifications-fetched",
    "notifications-cleared" = "notifications-cleared",
    "notification-cleared" = "notification-cleared",
    "category-fetched" = "category-fetched",
    "category-add" = "category-add",
    "category-update" = "category-update",
    "category-delete" = "category-delete",
    "category-status" = "category-status",

    "product-fetched" = "product-fetched",
    "product-add" = "product-add",
    "product-update" = "product-update",
    "product-delete" = "product-delete",
    "product-status" = "product-status",

    "country-fetched" = "country-fetched",
    "country-add" = "country-add",
    "country-update" = "country-update",
    "country-delete" = "country-delete",
    "country-status" = "country-status",
    "state-fetched" = "state-fetched",
    "state-add" = "state-add",
    "state-update" = "state-update",
    "state-delete" = "state-delete",
    "state-status" = "state-status",
    "city-fetched" = "city-fetched",
    "city-add" = "city-add",
    "city-update" = "city-update",
    "city-delete" = "city-delete",
    "city-status" = "city-status",

    "role-fetched" = "role-fetched",
    "role-add" = "role-add",
    "role-update" = "role-update",
    "role-delete" = "role-delete",
    "role-status" = "role-status",

    "permission-fetched" = "permission-fetched",
    "permission-add" = "permission-add",
    "permission-update" = "permission-update",
    "permission-delete" = "permission-delete",
    "permission-status" = "permission-status",

    "unit-fetched" = "unit-fetched",
    "unit-add" = "unit-add",
    "unit-update" = "unit-update",
    "unit-delete" = "unit-delete",
    "unit-status" = "unit-status",

    "banner-fetched" = "banner-fetched",
    "banner-add" = "banner-add",
    "banner-update" = "banner-update",
    "banner-delete" = "banner-delete",
    "banner-status" = "banner-status",


    "incorrect-password" = "incorrect-password",
    "password-mismatch" = "password-mismatch",
    "password-updated" = "password-updated",
    "update-failed" = "update-failed",
    "profile-img-updated" = "profile-img-updated",

    "missing-params" = "missing-params",
    "token-expired" = "token-expired",
    "token-invalid" = "token-invalid",

    "customer-fetched" = "customer-fetched",
    "customer-add" = "customer-add",
    "customer-updated" = "customer-updated",
    "customer-deleted" = "customer-deleted",
    "customer-status" = "customer-status",


    "search-fetched" = "search-fetched",

    "wallet-balance-fetched" = "wallet-balance-fetched",
    "wallet-recharge-success" = "wallet-recharge-success",
    "transactions-fetched" = "transactions-fetched",


    "watchlist-fetched" = "watchlist-fetched",
    "watchlist-add" = "watchlist-add",
    "watchlist-update" = "watchlist-update",
    "watchlist-delete" = "watchlist-delete",
    "watchlist-status" = "watchlist-status",
    "watchlist-item-add" = "watchlist-item-add",
    "watchlist-item-remove" = "watchlist-item-remove",

    "product-requested" = "product-requested",
    "product-request-fetched" = "product-request-fetched",
    "product-request-add" = "product-request-add",
    "product-request-update" = "product-request-update",
    "product-request-delete" = "product-request-delete",
    "product-request-status" = "product-request-status",

    "offer-fetched" = "offer-fetched",
    "offer-add" = "offer-add",
    "offer-update" = "offer-update",
    "offer-delete" = "offer-delete",
    "offer-status" = "offer-status",
    "report-issue" = "report-issue",

    "faq-fetched" = "faq-fetched",
    "faq-add" = "faq-add",
    "faq-update" = "faq-update",
    "faq-delete" = "faq-delete",
    "faq-status" = "faq-status",

    "attribute-fetched" = "attribute-fetched",
    "attribute-add" = "attribute-add",
    "attribute-update" = "attribute-update",
    "attribute-delete" = "attribute-delete",
    "attribute-status" = "attribute-status",

    "settings-saved" = "settings-saved",
    "settings-fetched" = "settings-fetched",

    "team-fetched" = "team-fetched",
    "team-add" = "team-add",
    "team-update" = "team-update",
    "team-delete" = "team-delete",
    "team-status" = "team-status",
}
