export enum ServerMessagesEnum {
    "server-error" = "server-error",
    "no-file-provided"="no-file-provided",
    "not-found" = "not-found",
    "required-iv" = "required-iv",
    "permission-denied" = "permission-denied",
    "user-bc"="user-bc",
    "user-bl" = "user-bl",
    "user-dl" = "user-dl",
    "user-it" = "user-it",
    "user-ua" = "user-ua",
    "user-nf" = "user-nf",
    "user-fetched" = "user-fetched",
    "user-add" = "user-add",
    "user-update" = "user-update",
    "user-delete" = "user-delete",
    "user-status" = "user-status",
    "category-fetched" = "category-fetched",
    "category-add" = "category-add",
    "category-update" = "category-update",
    "category-delete" = "category-delete",
    "category-status" = "category-status",
    "country-fetched" = "country-fetched",
    "country-add" = "country-add",
    "country-update" = "country-update",
    "country-delete" = "country-delete",
    "country-status"="country-status"
}
