export enum ServerMessagesEnum {
    "server-error" = "server-error",
    "no-file-provided"="no-file-provided",
    "not-found" = "not-found",
    "required-iv" = "required-iv",
    "permission-denied" = "permission-denied",
    "user-bc"="user-bc",
    "user-bl" = "user-bl",
    "user-dl" = "user-dl",
    "user-it" = "user-it",
    "user-ua" = "user-ua",
    "user-nf" = "user-nf",
    "email-already-exists" = "email-already-exists",
    "invalid-password" = "invalid-password",
    "logged-in"="logged-in",
    "user-fetched" = "user-fetched",
    "user-add" = "user-add",
    "user-update" = "user-update",
    "user-delete" = "user-delete",
    "user-status" = "user-status",
    "category-fetched" = "category-fetched",
    "category-add" = "category-add",
    "category-update" = "category-update",
    "category-delete" = "category-delete",
    "category-status" = "category-status",

    "product-fetched" = "product-fetched",
    "product-add" = "product-add",
    "product-update" = "product-update",
    "product-delete" = "product-delete",
    "product-status" = "product-status",

    "country-fetched" = "country-fetched",
    "country-add" = "country-add",
    "country-update" = "country-update",
    "country-delete" = "country-delete",
    "country-status" = "country-status",
    "state-fetched" = "state-fetched",
    "state-add" = "state-add",
    "state-update" = "state-update",
    "state-delete" = "state-delete",
    "state-status" = "state-status",
    "city-fetched" = "city-fetched",
    "city-add" = "city-add",
    "city-update" = "city-update",
    "city-delete" = "city-delete",
    "city-status" = "city-status",

    "role-fetched" = "role-fetched",
    "role-add" = "role-add",
    "role-update" = "role-update",
    "role-delete" = "role-delete",
    "role-status" = "role-status",

    "permission-fetched" = "permission-fetched",
    "permission-add" = "permission-add",
    "permission-update" = "permission-update",
    "permission-delete" = "permission-delete",
    "permission-status" = "permission-status",

    "unit-fetched" = "unit-fetched",
    "unit-add" = "unit-add",
    "unit-update" = "unit-update",
    "unit-delete" = "unit-delete",
    "unit-status"="unit-status",
    "incorrect-password" = "incorrect-password",
    "password-mismatch" = "password-mismatch",
    "password-updated" = "password-updated",
    "update-failed" = "update-failed",
    "profile-img-updated" = "profile-img-updated",
    "bannerimg-create" = "bannerimg-create",
    "bannerimg-update" = "bannerimg-update",
    "bannerimg-delete" = "bannerimg-delete",
    "bannerimg-not-found" = "bannerimg-not-found",
    "banner-status-update" = "banner-status-update",
    "missing-params" = "missing-params",
    "watchlist-notfound" = "watchlist-notfound",
    "watchlist-delete" = "watchlist-delete",
    "token-expired" = "token-expired",
    "token-invalid" = "token-invalid",

    "banner-fetched" = "banner-fetched",

    "customer-fetched" = "customer-fetched",
    "customer-add" = "customer-add",
    "customer-updated" = "customer-updated",
    "customer-deleted" = "customer-deleted",
    "customer-status" = "customer-status",

    "productwatch-fetched" = "productwatch-fetched",
    "productwatch-create" = "productwatch-create",
    "productwatch-update" = "productwatch-update",
    "productwatch-notfound" = "productwatch-notfound",
    "productwatch-delete" = "productwatch-delete",
    "search-fetched" = "search-fetched",

    "wallet-fetched" = "wallet-fetched",
    "wallettrans-fetched" = "wallettrans-fetched",
    "watchlist-fetched" = "watchlist-fetched",
    "watchlist-create" = "watchlist-create",
    "watchlist-update" = "watchlist-update"
}
